### ISSUE TITLE
Packaging for nixpkgs: Chromium download at runtime and system compatibility

### ISSUE THREAD

**Issue by louis-thevenet** [Skardyy/mcat#3]
Hello !

I'm in the process of packaging this project to [nixpkgs](https://github.com/nixos/nixpkgs/) through https://github.com/NixOS/nixpkgs/pull/402539.

NixOS systems cannot run dynamically linked programs, which means that a downloaded chromium won't run.
Additionally, forcing its download at runtime is not really conventional. 

There are alternatives, here are some:
- Using the system's browser (through `xdg-open` on Linux for example) but since you use `chromiumoxide` it's likely not feasible
- Making a config option to specify a path to chromium
- Making the download of chromium a cargo feature (to allow us to build `mcat` without it)

This list is not exhaustive.

Unrelated feature suggestion:
Have you consider using [termimad](https://github.com/Canop/termimad) to pretty print Markdown ? Could be a nice addition =)

**Comment by Skardyy** [comment]
👋 hey!

> NixOS systems cannot run dynamically linked programs, which means that a downloaded chromium won't run.
Additionally, forcing its download at runtime is not really conventional.  

Then, I'd assume the automatic download of FFmpeg would also be a problem?

I'm actually not familiar with how NixOS works
but from what I understood, making the auto download behind a cargo feature should fix it?
I was actually thinking on doing this anyways - forcing auto download isn't actually ideal tbh

> Unrelated feature suggestion:
Have you consider using [termimad](https://github.com/Canop/termimad) to pretty print Markdown ? Could be a nice addition =)

that actually sounds cool, definitely going to take a look on it!

**Comment by louis-thevenet** [comment]
> Then, I'd assume the automatic download of FFmpeg would also be a problem?

Yep, you're right

> making the auto download behind a cargo feature should fix it?

It would allow me to disable the feature since it doesn't work for nixpkgs users, which would fix the problem :)
What would be ideal is no forced download + an error suggesting to install the dependency (which already exists I think so that's nice)

Thank you for the quick response!

**Comment by Skardyy** [comment]
ok from some testing i did notice it can be quite annoying to get chromium to work on ubuntu (maybe because of outdated version, chromiumoxide fails)

I was thinking on making the auto download not a feature, but a separate function, e.g:
mcat fetch ffmpeg ~ mcat fetch chromium.
so users won't need to recompile in such annoying case.

would that still work for NixOS?

**Comment by louis-thevenet** [comment]
> I was thinking on making the auto download not a feature, but a separate function, e.g:
mcat fetch ffmpeg ~ mcat fetch chromium.

Yup that's an option too =)

> would that still work for NixOS?
It will still fail saying chromium / ffmpeg isn't installed, just now it will also suggest installing using the auto fetch (for other platforms other then NixOS)

Sure, I think it should say something like "install the dependencies or use the auto fetch if your system allows it", a clear hint at what to do for every type of users

This seems top be a reasonable solution

**Comment by louis-thevenet** [comment]
It's done, thank you for the help :)
